[package]
name = "gutenberg"
version = "0.0.7"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
readme = "README.md"
description = "Static site generator"
homepage = "https://github.com/Keats/gutenberg"
repository = "https://github.com/Keats/gutenberg"
keywords = ["static", "site", "generator", "blog"]

[[bin]]
name = "gutenberg"

[dependencies]
error-chain = "0.10"
clap = "2"
walkdir = "1"
pulldown-cmark = "0"
regex = "0.2"
lazy_static = "0.2"
glob = "0.2"
serde = "1.0"
serde_derive = "1.0"
# tera = { path = "../tera" }
# tera = { git = "https://github.com/Keats/tera" }
tera = "0.10"
slug = "0.1"
syntect = { version = "1", features = ["static-onig"] }
chrono = "0.3"
toml = "0.4"
term-painter = "0.2"
base64 = "0.6"
rayon = "0.8"

# Below is for the serve cmd
staticfile = "0.4"
iron = "0.5"
mount = "0.3"
notify = "4"
ws = "0.7"

[dev-dependencies]
tempdir = "0.3"
